FROM mariadb:lts

ARG TARGETPLATFORM
ARG BINARY_NAME

# Install pigz
RUN apt-get update && apt-get install -y pigz && rm -rf /var/lib/apt/lists/*

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy the Pre-built binary file from GoReleaser
COPY $TARGETPLATFORM/$BINARY_NAME ./app

# Command to run the executable
ENTRYPOINT ["./app"]

