name: PR

on:
  pull_request:
    branches: [master]

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Login to GitHub Container registry
        if: github.actor != 'dependabot[bot]'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: "~> v2"
          args: release --snapshot

      - name: Upload to S3
        uses: capcom6/upload-s3-action@master
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          endpoint: ${{ secrets.AWS_ENDPOINT }}
          source_files: |
            dist/mariadb-backup-s3_Windows_i386.zip
            dist/mariadb-backup-s3_Linux_arm64.tar.gz
            dist/mariadb-backup-s3_Darwin_arm64.tar.gz
            dist/mariadb-backup-s3_Windows_x86_64.zip
            dist/mariadb-backup-s3_Linux_x86_64.tar.gz
            dist/mariadb-backup-s3_Windows_arm64.zip
            dist/mariadb-backup-s3_Darwin_x86_64.tar.gz
            dist/mariadb-backup-s3_Linux_i386.tar.gz
          destination_dir: ${{ github.repository }}/${{ github.event.pull_request.head.sha }}

      - name: Push images
        if: github.actor != 'dependabot[bot]'
        run: |
          docker tag ghcr.io/${{ github.repository }}:latest ghcr.io/${{ github.repository }}:pr-${{ github.event.pull_request.number }}
          docker push ghcr.io/${{ github.repository }}:pr-${{ github.event.pull_request.number }}

      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: Pull request artifacts

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## 🤖 Pull request artifacts

            | Platform          | File                                                                                                                               |
            | ----------------- | ---------------------------------------------------------------------------------------------------------------------------------- |
            | 🐳 Docker         | [GitHub Container Registry](https://ghcr.io/${{ github.repository }}:pr-${{ github.event.pull_request.number }})                   |
            | 🍎 Darwin arm64   | [mariadb-backup-s3_Darwin_arm64.tar.gz](https://github.capcom.me/${{ github.repository }}/${{ github.event.pull_request.head.sha }}/mariadb-backup-s3_Darwin_arm64.tar.gz)   |
            | 🍎 Darwin x86_64  | [mariadb-backup-s3_Darwin_x86_64.tar.gz](https://github.capcom.me/${{ github.repository }}/${{ github.event.pull_request.head.sha }}/mariadb-backup-s3_Darwin_x86_64.tar.gz) |
            | 🐧 Linux arm64    | [mariadb-backup-s3_Linux_arm64.tar.gz](https://github.capcom.me/${{ github.repository }}/${{ github.event.pull_request.head.sha }}/mariadb-backup-s3_Linux_arm64.tar.gz)     |
            | 🐧 Linux i386     | [mariadb-backup-s3_Linux_i386.tar.gz](https://github.capcom.me/${{ github.repository }}/${{ github.event.pull_request.head.sha }}/mariadb-backup-s3_Linux_i386.tar.gz)       |
            | 🐧 Linux x86_64   | [mariadb-backup-s3_Linux_x86_64.tar.gz](https://github.capcom.me/${{ github.repository }}/${{ github.event.pull_request.head.sha }}/mariadb-backup-s3_Linux_x86_64.tar.gz)   |
            | 🪟 Windows arm64  | [mariadb-backup-s3_Windows_arm64.zip](https://github.capcom.me/${{ github.repository }}/${{ github.event.pull_request.head.sha }}/mariadb-backup-s3_Windows_arm64.zip)       |
            | 🪟 Windows i386   | [mariadb-backup-s3_Windows_i386.zip](https://github.capcom.me/${{ github.repository }}/${{ github.event.pull_request.head.sha }}/mariadb-backup-s3_Windows_i386.zip)         |
            | 🪟 Windows x86_64 | [mariadb-backup-s3_Windows_x86_64.zip](https://github.capcom.me/${{ github.repository }}/${{ github.event.pull_request.head.sha }}/mariadb-backup-s3_Windows_x86_64.zip)     |

          edit-mode: replace
